apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    resources:
      requests:
          ephemeral-storage: "16Gi"
          memory: "1024Mi"
      limits:
          ephemeral-storage: "16Gi"
          memory: "4096Mi"
