apiVersion: v1
kind: Pod
metadata:
  labels:
    docker: phaedra2-builder-kaniko
spec:
  imagePullSecrets:
    - name: registry-robot
  volumes:
    - name: kaniko-dockerconfig
      secret:
        secretName: registry-robot
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.9.1-debug
    command:
    - cat
    tty: true
    resources:
      requests:
          memory: "1024Mi"
      limits:
          memory: "4096Mi"
    imagePullPolicy: Always
    volumeMounts:
      - name: kaniko-dockerconfig
        mountPath: /kaniko/.docker/config.json
        subPath: .dockerconfigjson